Add CMake build system and
ACCESS-NRI/GFDL-generic-tracers pull request #17
Opened 2024-11-19 02:46 UTC by harshula

2024-11-20 02:48 UTC, micaeljtoliveira requested changes
@harshula Here are some comments plus a couple of questions.

2024-11-20 02:48 UTC, micaeljtoliveira commented on CMakeLists.txt
> +install(DIRECTORY ${CMAKE_Fortran_MODULE_DIRECTORY}/ TYPE INCLUDE)
Will this install the files to `CMAKE_INSTALL_INCLUDEDIR`?

2024-11-20 02:48 UTC, micaeljtoliveira commented on CMakeLists.txt
> +install(TARGETS gtracers)
Would be good to also exports the targets here.

2024-11-20 02:48 UTC, micaeljtoliveira commented on CMakeLists.txt
> +add_library(gtracers STATIC)
For now I think using a static library is fine, but at some point we need to have a serious discussion about shared libraries and how we want to tackle them. They will be critical to speed up the launch of MPI jobs across hundreds of nodes and to reduce the memory footprint.

2024-11-20 11:10 UTC, harshula commented on gfdl-generic-tracers.pc.in
> +Requires.private: mocsy
Are there any other static libraries required by GFDL-generic-tracers?

2024-11-28 05:20 UTC, harshula commented on CMakeLists.txt
> +install(DIRECTORY ${CMAKE_Fortran_MODULE_DIRECTORY}/ TYPE INCLUDE)
```
[root@2b59a8c74ebf opt]# ls /opt/release/linux-rocky8-x86_64/intel-2021.2.0/access-generic-tracers-git.dev_2024.11.0_2024.11.0-ro4isgis6rqxx4qm42fluune6baab5b4/include/ | cat -
fms_coupler_util.mod
fms_ocmip2_co2calc_mod.mod
g_tracer_utils.mod
generic_abiotic.mod
generic_age.mod
generic_argon.mod
generic_bling.mod
generic_blres.mod
generic_cfc.mod
generic_cobalt.mod
generic_ergom.mod
generic_minibling_mod.mod
generic_sf6.mod
generic_topaz.mod
generic_tracer.mod
generic_wombatlite.mod
```

2024-11-28 05:23 UTC, harshula commented on CMakeLists.txt
> +add_library(gtracers STATIC)
It would be great to get clarity on performance impact of static Vs shared libraries.

2024-11-28 22:46 UTC, micaeljtoliveira commented on CMakeLists.txt
> +add_library(gtracers STATIC)
The impact is hard to estimate and we'll only know for sure once we actually try it, but we know it  will depend on a few things, like the filesystem, the number of MPI tasks and the executable size. The executable size will in turn depend on the model itself but also on which optimisation flags are used, debug symbols etc, but it's quite common for it to be in the order of a few hundred Mb when using static libraries.

We also know some configurations will run on a few thousands of cores. That means if you have an executable that is a few hundred Mb in size, we are talking about tens to hundreds of Gb in unnecessary memory footprint. It also means that, when launching the job, which will happen often, we'll have thousands of processes loading the same file from disk. Even if we are talking of 1-2% in memory footprint and wall-time (could be more!), using shared libraries is a low-hanging fruit that is just there for us to grab.

2024-11-28 22:46 UTC, micaeljtoliveira commented on CMakeLists.txt
> +install(DIRECTORY ${CMAKE_Fortran_MODULE_DIRECTORY}/ TYPE INCLUDE)
Great, learned something new today :)

2024-11-28 22:46 UTC, micaeljtoliveira commented on gfdl-generic-tracers.pc.in
> +Requires.private: mocsy
I think FMS, as installed in your spack environment, is also static, no?

Sorry if this is a naive question, as I'm not really an expert in pkgconfig. I was just expecting to see netCDF and FMS listed somewhere here.

2024-11-29 08:04 UTC, harshula commented on gfdl-generic-tracers.pc.in
> +Requires.private: mocsy
Good catch! I was expecting FMS to default to shared. Are you OK with FMS being built as a shared library?

2024-12-02 00:24 UTC, micaeljtoliveira commented on gfdl-generic-tracers.pc.in
> +Requires.private: mocsy
Yes, all good to have FMS built as shared from my side.

Just for my understanding, the reason for not adding FMS (once built as shared) and netCDF here is because Spack will directly or indirectly take care of that?

2024-12-02 01:03 UTC, harshula commented on gfdl-generic-tracers.pc.in
> +Requires.private: mocsy
`Requires.private` is covered in the FAQ at https://people.freedesktop.org/~dbn/pkg-config-guide.html . In our case Spack is generating mocsy's pkgconf pc file. If it wasn't, we would need to populate `Libs.private`.

2024-12-02 01:14 UTC, micaeljtoliveira commented on gfdl-generic-tracers.pc.in
> +Requires.private: mocsy
Thanks for the link. I think my question is answered here:

> Libs: The link flags specific to this package and any required libraries that don't support pkg-config. The same rule as Cflags applies here.

the key part being **libraries that don't support pkg-config**.

2025-04-04 06:22 UTC, harshula commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
Hi @micaeljtoliveira , 

* Spack's `netcd-fortran` package is built using autotools.
* If we use `find_package(FMS COMPONENTS R8 REQUIRED)`, CMake can't find `netcdf` and the build fails with:
```
CMake Error at /opt/release/linux-rocky8-x86_64/intel-2021.10.0/cmake-3.24.4-l4wz2zzrh6mqroxffa25vifqmpzxainq/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NetCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NetCDF" with any
  of the following names:

    NetCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
  "NetCDF_DIR" to a directory containing one of the above files.  If "NetCDF"
  provides a separate development package or SDK, be sure it has been
  installed.
```
* It looks like we'll have to use pkgconfig with FMS, unless you know of another way that doesn't involve adding `FindNetCDF.cmake` to this repository?

2025-04-04 12:02 UTC, harshula commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
Hi @micaeljtoliveira , 

* Spack's `netcd-fortran` package is built using autotools.
* If we use `find_package(FMS COMPONENTS R8 REQUIRED)`, CMake can't find `netcdf` and the build fails with:
```
CMake Error at /opt/release/linux-rocky8-x86_64/intel-2021.10.0/cmake-3.24.4-l4wz2zzrh6mqroxffa25vifqmpzxainq/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NetCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NetCDF" with any
  of the following names:

    NetCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
  "NetCDF_DIR" to a directory containing one of the above files.  If "NetCDF"
  provides a separate development package or SDK, be sure it has been
  installed.
```
* It looks like we'll have to use pkgconfig with FMS, unless you know of another way that doesn't involve adding `FindNetCDF.cmake` to this repository?

2025-04-04 12:15 UTC, harshula commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
* ACCESS-NRI's FMS branch `mom5` now contains a backport of the CMake build system from upstream FMS. The objective is to keep the build system of ACCESS-NRI's FMS branch `mom5`  in-sync with upstream. So, we won't be trying to export FindNetCDF.cmake in ACCESS-NRI's FMS branch `mom5`, unless upstream adds that feature.

2025-04-07 05:31 UTC, micaeljtoliveira commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
@harshula Can you try building this using the `fix_cmake_export` branch that I just pushed to our fork of FMS?  (https://github.com/ACCESS-NRI/FMS/tree/fix_cmake_export)

If that works, I'll create a PR for inclusion of the fix upstream.

2025-04-07 13:45 UTC, harshula commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
Hi @micaeljtoliveira ,
```
# spack install access-generic-tracers@git.dev-2025.04.0 %intel@2021.10.0 target=x86_64 ^access-fms@git.fix_cmake_export
...
==> Installing access-fms-git.fix_cmake_export=2025.04.001-git.1-7groxqspmcj7wiktqsf4rrqdtiay2lkm [36/37]
==> No binary for access-fms-git.fix_cmake_export=2025.04.001-git.1-7groxqspmcj7wiktqsf4rrqdtiay2lkm found: installing from source
==> No patches needed for access-fms
==> access-fms: Executing phase: 'cmake'
==> access-fms: Executing phase: 'build'
==> access-fms: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

2 errors found in build log:
...
CMake Error at cmake_install.cmake:77 (file):
  file INSTALL cannot find
  "/tmp/root/spack-stage/spack-stage-access-fms-git.fix_cmake_export_2025.04.001-git.1-7groxqspmcj7wiktqsf4rrqdtiay2lkm/spack-src/FindNetCDF.cmake":
  No such file or directory.


make: *** [Makefile:103: install] Error 1
```

For testing, you can build a spack-dev Docker container by using: https://github.com/ACCESS-NRI/build-ci/tree/main/containers .

2025-04-07 22:02 UTC, micaeljtoliveira commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
Should be fixed.

2025-04-08 01:12 UTC, harshula commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
I'll test building FMS as a dynamic library to see if we can avoid all these netcdf issues.

2025-04-13 22:57 UTC, micaeljtoliveira commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
@harshula Just to let you know, the fix to the FMS build system has been merged upstream. Once there's a new FMS release, it should be possible to do

`find_package(FMS COMPONENTS R8 REQUIRED)`

from a package that does not use netCDF itself without encountering any errors, regardless of netCDF-Fortran being built with CMake or not.

2025-04-15 01:26 UTC, harshula commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
Hi @micaeljtoliveira , Thanks for doing that, but we probably won't need it. Last week I tested successful builds with dynamic libraries with pkgconfig with no netcdf dependency. I'll write it up in a comment.

2025-05-13 03:24 UTC, dougiesquire commented on CMakeLists.txt
> +pkg_check_modules(FMS REQUIRED IMPORTED_TARGET "FMS")
This is now done in https://github.com/ACCESS-NRI/GFDL-generic-tracers/pull/17/commits/80e2b9de0d4074adbe1d32386c4db1eb526ef11f

2025-05-13 03:25 UTC, dougiesquire commented on CMakeLists.txt
> +install(TARGETS gtracers)
Done in https://github.com/ACCESS-NRI/GFDL-generic-tracers/pull/17/commits/5710eff8e64b3e0cc6b762788bf7c74ddc5719f3

2025-05-13 03:30 UTC, dougiesquire commented
This has been tested fairly extensively in ACCESS models. Results here: https://github.com/ACCESS-NRI/spack-packages/pull/238#issuecomment-2874770877

2025-05-13 03:34 UTC, dougiesquire approved these changes
One change below and then this is good to go from my perspective (noting that I haven't tested the PkgConfig).

2025-05-13 03:34 UTC, dougiesquire commented on CMakeLists.txt
> +  generic_tracers/generic_WOMBATlite.F90
WOMBATmid has since been added

```suggestion
  generic_tracers/generic_WOMBATlite.F90
  generic_tracers/generic_WOMBATmid.F90
```

2025-05-13 04:10 UTC, micaeljtoliveira submitted a review, later dismissed

2025-05-13 23:39 UTC, dougiesquire commented on CMakeLists.txt
> +  generic_tracers/generic_WOMBATlite.F90
Done in [0d984a2](https://github.com/ACCESS-NRI/GFDL-generic-tracers/pull/17/commits/0d984a2ef67a36737a574176cc3ce308ad8e7305)

2025-05-13 23:41 UTC, dougiesquire commented
Sorry @micaeljtoliveira, would you mind re-approving? I just [added one addition source](https://github.com/ACCESS-NRI/GFDL-generic-tracers/pull/17/commits/0d984a2ef67a36737a574176cc3ce308ad8e7305) and tidied some commit messages.

@harshula are you happy for me to merge with @micaeljtoliveira's approval?

2025-05-13 23:47 UTC, dougiesquire approved these changes

2025-05-14 00:18 UTC, micaeljtoliveira submitted a review, later dismissed

2025-05-14 02:53 UTC, harshula commented
Hi @dougiesquire , In your testing, did you build access-fms as a dynamic library or a static library?

2025-05-14 03:01 UTC, dougiesquire commented
> Hi @dougiesquire , In your testing, did you build access-fms as a dynamic library or a static library?

I just used the default, so static

2025-05-20 23:11 UTC, dougiesquire approved these changes

2025-06-02 04:04 UTC, aidanheerdegen commented
I've removed myself as a reviewer as this has gone down some quite specific niches and I'm not sure I am the best to approve. Having said which, if you feel you've addressed all the feedback and need a big green tick to get this moving happy to do so.

2025-07-08 03:30 UTC, dougiesquire commented
@harshula, once we get @JorgeG94's [update for the mocsy dependency](https://github.com/ACCESS-NRI/GFDL-generic-tracers/pull/40) into this branch are you okay for me to (squash and) merge?

This has now been pretty well tested. If there's additional testing you want to do, could it continue after merging?

2025-07-08 14:51 UTC, harshula commented
Hi @dougiesquire , I'll try to finish my testing this week and I'll merge it.

2025-07-22 00:39 UTC, dougiesquire commented
My preference is to "squash and merge" to minimize the number of commits we carry ahead of upstream. Are you okay with that?

2025-07-22 02:23 UTC, harshula commented
Hi @dougiesquire , A merge commit is different from a 'rebase and merge', where all the commits appear linearly in the git commit history and hence difficult to isolate to a single PR/merge. The merge commit provides isolation of a series of commits. e.g. `git revert` of the merge commit reverts the entire series of commits. I'll be doing a merge commit to keep the functional changes in separate commits but the series will isolated and grouped together via the merge commit. i.e. If you view the log via a graphical/tree diff, you'll clearly see this series of commits grouped together.

2025-07-22 02:32 UTC, dougiesquire commented
Yup, I understand that difference thanks. But I said "squash and merge", not "rebase and merge". As I mentioned, we're trying to keep clean and minimize the commits on main that are ahead of upstream. You can include the PR number in the squashed commit message (the Github UI defaults to this) so that the individual commits in this PR can still be easily found.

2025-07-22 03:12 UTC, dougiesquire commented
> Your reasoning sounded like you are confusing a merge commit with 'rebase and merge'. Try using git log --graph. The merge commit achieves the isolation you want and additionally keeps the functional changes in separate commits.

Nah I'm not confusing them. I'm just trying to keep the commits on `main` clean/minimal and as linear as possible.

2025-07-23 01:17 UTC, dougiesquire commented
Apologies, testing was held up by a dependency bug in [model-config-tests](https://github.com/ACCESS-NRI/model-config-tests/pull/169) and [Payu](https://github.com/payu-org/payu/issues/613)

2025-07-23 02:31 UTC, dougiesquire approved these changes
Summary of results of [testing with `dev-1deg_jra55_ryf+wombatlite` config](https://github.com/ACCESS-NRI/access-om2-configs/pull/196):
- Adding support for shared fms, mocsy, gtracers libs _does not_ change answers (expected)
- Building ACCESS-OM2 with shared fms, mocsy, gtracers libs _does_ change answers (by a tiny amount)

Thanks for this long slog @harshula. I'm happy to merge. Don't forget to rebase :)

2025-07-23 03:09 UTC, merged